### ISSUE TITLE
`$many_many_extraFields` not shown

### ISSUE THREAD

**Issue by anselmdk** [froog/SilverGraph#6]
@froog as you know, I love your module. I'm just missing one thing - `$many_many_extraFields` are not shown - do you think it would be a big thing to implement?

**Comment by anselmdk** [comment]
I want to support this a little, so I just posted a USD 50 bounty on it: https://www.bountysource.com/issues/15272150-many_many_extrafields-not-shown

**Comment by froog** [comment]
Solution from @edlinklater has been merged, good work!

**Comment by anselmdk** [comment]
Great. @edlinklater, don't forget to claim your bounty :)

**Comment by anselmdk** [comment]
@edlinklater this seems to be broken in SilverStripe 4 (see https://github.com/froog/SilverGraph/pull/18), I've spent quite some time debugging it, but am giving up for now... Any pointers would be appreciated!
