### ISSUE TITLE
SilverStripe 3.2 support

### ISSUE THREAD

**Issue by anselmdk** [froog/SilverGraph#9]
This module doesn't work out-of-the-box with SilverStripe 3.2.
**Firstly** you need to add the controller, due to [URL routing by controller name having been removed](https://docs.silverstripe.org/en/3.2/changelogs/3.2.0/#api-removed-url-routing-by-controller-name).

This could be done like this:

```
Director:
  rules:
    'Silvergraph//$Action' : 'Silvergraph'
```

**Secondly** the graph looks to be messed up, see this example for `/Silvergraph/png?location=mysite,cms&inherited=1&exclude=SiteTree`:

![png](https://cloud.githubusercontent.com/assets/1316533/11073451/f7232458-87ea-11e5-9d37-90f76b63d7ea.png)

**Comment by anselmdk** [comment]
Just added a USD 25 bounty on this one.
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=28137067)](https://www.bountysource.com/issues/28137067-silverstripe-3-2-support?utm_source=28137067&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by froog** [comment]
Ok @anselmdk, test it now - I've added in the url routing and fixed the bug (was a naming conflict with 3.2)

Cheers,
Dan

**Comment by anselmdk** [comment]
That's beautiful @froog, seems to work perfectly.

**Comment by anselmdk** [comment]
You should be able to claim the bounty now.
